services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - runtime
    environment:
      - WEBUI_SECRET_KEY=your_secret_key
      - OPENAI_API_BASE_URL=http://runtime:8080/openai/demo/v1
      - OPENAI_API_KEY=your_token_here # contenox require auth only if the TOKEN is provided via environment variable
volumes:
  open-webui-data:
