name: Build and Push Docker image to GHCR

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Debug metadata output
        run: echo "The version tag is ${{ steps.vars.outputs.TAG }}"

      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.TAG }}
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/runtime-api:${{ steps.vars.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/runtime-api:latest
